version: '3.7'

services:
  db:
    image: mongo
    container_name: db
    ports:
      - 27017:27017
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    tty: true


