# version: '3.7'

# services:
#   db:
#     image: mongo
#     container_name: db
#     ports:
#       - 27017:27017
#     restart: always

#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: root
#       MONGO_INITDB_DATABASE: admin
#     tty: true

version: '3.7'

services:
  app:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: back-end
    environment:
      KEY_MASTER_JWT: tallos123
      PORT : 3000
    ports:
      - 3000:3000
      - 3001:3001
    restart: always
    links:
      - db
    depends_on:
      - db
    tty: true
    networks: 
      - projeto-gerenciador-funcionarios

  db:
    image: mongo:4.4
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - mongodb_server_data:/data/db
      - mongodb_server_data:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    networks: 
      - projeto-gerenciador-funcionarios

volumes:
  mongodb_server_data: 
  
networks:
  projeto-gerenciador-funcionarios:
    driver: bridge

